name = "Mixtape"
uuid = "17c23775-69b5-4366-8053-0c64bad4914c"
authors = ["McCoy R. Becker <mccoybecker@gmail.com> and Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"

[compat]
GPUCompiler = "0.9"
LLVM = "3.0"
julia = "1.6"
